name: iic
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit=10.2
  - jsonschema=3.2.0
  - opencv=4.5.5
  - numpy=1.19.5
  - pandas=1.0.1
  - pillow=9.1.0
  - pip=19.3.1
  - python=3.7.6
  - pytorch=1.5.0
  - pyyaml=5.2
  - scikit-image=0.16.2
  - scipy=1.7.3
  - tifffile=2022.3.25
  - torchvision=0.6.0
  - pip:
      - suffix-trees==0.3.0
